#
# Docker Compose file to set up rapidly an isolated 
# nyaa.si environment
#
version: "3"
services:
  nyaa:
    build: .
    ports:
    - "5500:5500"
    environment:
      MYSQL_HOST: nyaa-db
      MYSQL_USER: test
      MYSQL_PASS: test123
      #MYSQL_DATABASE:
      #SITE_FLAVOR:
    depends_on:
      - nyaa-db

  nyaa-db:
    image: "mariadb:10.0"
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: nyaav2
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123